### ISSUE TITLE
What does your deploy task look like using these?

### ISSUE THREAD

**Issue by dareenzo** [rafaelstz/deployer-magento2#19]
Hey,

thanks for the recipe, it well-structured and has all is needed for Magento.

Could you provide an example of how you plumb it all together -- you deploy task specifically.

Thanks

**Comment by dareenzo** [comment]
Its here: https://github.com/rafaelstz/deployer-magento2/blob/master/deploy.php#L96-L113

**Comment by rafaelstz** [comment]
Hi @dareenzo,

If you have some suggestion, please let me know!

**Comment by dareenzo** [comment]
Allowing the user to specify deployment languages through some variable would be great!

**Comment by rafaelstz** [comment]
Excellent I added it as a new feature to be launched, thank you! 🙌 😄

**Comment by rafaelstz** [comment]
Hey @dareenzo,

Now it's accepting languages too I updated the [README](https://github.com/rafaelstz/deployer-magento2) file.

Thanks again for suggesting it.
