### ISSUE TITLE
setup:upgrade fail

### ISSUE THREAD

**Issue by leon-fb** [rafaelstz/deployer-magento2#35]
In recipes/database.php, there have been put magerun_params variable ( [link](https://github.com/rafaelstz/deployer-magento2/commit/6be6271dc5d363f55e1dd1e9573db3f2a15a63a5) ). However, this variable is also present in the 2 setup:upgrade tasks, which actually use magento_bin and not magerun.

Magento gives an error due to non existing commandline option, and deployment fails due to this.

**Comment by brendanbellcentaur** [comment]
Hi,

Yes im having the  same issue now. Before this update deployment works fine. 
Now I get the following errors when running deployment.

Is there  an additional parameter  we must add into the deploy.php file?

If  yes, what?

thanks

--------------------------------------------------------------------------

The command "cd /var/www/website_production/releases/20210127065405/ && /usr/bin/php7.4 bin/magento setup:upgrade --keep-generated --skip-root-check --root-dir=/var/www/website_production/re
  leases/20210127065405 -vvv" failed.

  Exit Code: 1 (General error)

  Host Name: STAGING - SITE

  ================
  Warning: Identity file /root/.ssh/id_rsa not accessible: No such file or directory.

  In ArgvInput.php line 201:

    [Symfony\Component\Console\Exception\RuntimeException]
    The "--skip-root-check" option does not exist.
